// Top-level build file for Ethereum Kit Android Library
buildscript {
    ext {
        kotlin_version = '1.8.0'
        room_version = '2.5.2'
        coroutines_version = '1.6.4'
    }
    
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    
    // Общая версия для всех модулей
    ext {
        library_version = '1.5.3'
        library_group = 'com.github.0xLabWallet'
    }
}

// Настройка для JitPack - общие переменные для всех модулей
subprojects {
    group = rootProject.ext.library_group
    version = rootProject.ext.library_version
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

